import { daysAgo, hoursAgo } from '@/utils'

export const INITIAL_TASKS = [
  {
    id: 't1',
    title: "Sage Morgan bilan bog'lanish",
    dealId: 'deal_001',
    dueDate: daysAgo(-1),
    done: false,
    assignee: 'u1',
  },
  {
    id: 't2',
    title: 'Texnik intervyu tashkil qilish',
    dealId: 'deal_002',
    dueDate: daysAgo(-2),
    done: false,
    assignee: 'u1',
  },
  {
    id: 't3',
    title: "Mijoz bilan interview o'tkazish",
    dealId: '',
    dueDate: daysAgo(0),
    done: false,
    assignee: 'u2',
  },
  {
    id: 't4',
    title: 'Taklif (proposal) tayyorlash',
    dealId: '',
    dueDate: daysAgo(-3),
    done: false,
    assignee: 'u3',
  },
  {
    id: 't5',
    title: 'Shartnoma imzolash',
    dealId: '',
    dueDate: daysAgo(2),
    done: true,
    assignee: 'u1',
  },
]

export const INITIAL_CALL_LEADS = [
  {
    id: 'lead-1',
    name: 'Murodjon Tashkentov',
    phone: '+998 90 123 45 67',
    source: 'telegram',
    agentId: 'u1',
    stage: 'unsorted',
    status: null,
    lastMessage: "Rahmat! Mana telegram kanalim...",
    tags: ['telegram'],
    createdAt: hoursAgo(2),
  },
  {
    id: 'lead-2',
    name: 'Sharifa Yoqubova',
    phone: '+998 91 234 56 78',
    source: 'call',
    agentId: 'u1',
    stage: 'unsorted',
    status: 'missed',
    lastMessage: '',
    tags: ["qo'ng'iroq"],
    createdAt: hoursAgo(5),
  },
  {
    id: 'lead-3',
    name: 'Akramjon Bekchanov',
    phone: '+998 93 345 67 89',
    source: 'telegram',
    agentId: 'u2',
    stage: 'new',
    status: null,
    lastMessage: 'Assalomu alaykum! Narxlar bilan qiziqaman.',
    tags: ['telegram', 'yangi'],
    createdAt: hoursAgo(6),
  },
  {
    id: 'lead-4',
    name: 'Mirziyo Qodirov',
    phone: '+998 94 456 78 90',
    source: 'website',
    agentId: 'u2',
    stage: 'new',
    status: null,
    lastMessage: "Saytdan so'rov yubordi.",
    tags: ['sayt'],
    createdAt: hoursAgo(9),
  },
  {
    id: 'lead-5',
    name: 'Abdujalil Rustamov',
    phone: '+998 95 549 86 86',
    source: 'call',
    agentId: 'u3',
    stage: 'unreachable',
    status: 'missed',
    lastMessage: '',
    tags: ["qo'ng'iroq", '3 marta'],
    createdAt: hoursAgo(20),
  },
  {
    id: 'lead-6',
    name: 'Jizzaxdan Gʻallorol',
    phone: '+998 94 196 98 38',
    source: 'call',
    agentId: 'u1',
    stage: 'interested',
    status: 'answered',
    lastMessage: "Narxlar bo'yicha qiziqish bildirdi.",
    tags: ["qo'ng'iroq", 'javob berildi'],
    createdAt: hoursAgo(18),
  },
  {
    id: 'lead-7',
    name: 'Akmal Surxandaryo',
    phone: '+998 99 428 97 90',
    source: 'call',
    agentId: 'u3',
    stage: 'interested',
    status: 'answered',
    lastMessage: 'Demo koʻrishni xohlaydi.',
    tags: ["qo'ng'iroq"],
    createdAt: hoursAgo(24),
  },
  {
    id: 'lead-8',
    name: 'Obidjon Mahmudov',
    phone: '+998 94 109 22 11',
    source: 'telegram',
    agentId: 'u2',
    stage: 'infoRequested',
    status: null,
    lastMessage: "Yillik obuna narxini so'radi.",
    tags: ['telegram'],
    createdAt: hoursAgo(30),
  },
  {
    id: 'lead-9',
    name: 'Urgut Nazarova',
    phone: '+998 90 450 51 12',
    source: 'website',
    agentId: 'u1',
    stage: 'infoRequested',
    status: null,
    lastMessage: 'Integratsiya haqida savol berdi.',
    tags: ['sayt'],
    createdAt: hoursAgo(36),
  },
  {
    id: 'lead-10',
    name: 'Diyorbek Nortojiyev',
    phone: '+998 97 777 12 34',
    source: 'call',
    agentId: 'u1',
    stage: 'converted',
    status: 'answered',
    lastMessage: 'Shartnoma imzolandi.',
    tags: ["qo'ng'iroq", 'mijoz'],
    createdAt: daysAgo(3),
  },
]

export const INITIAL_CANDIDATES = [
  {
    id: 'cand-1',
    name: 'Javlonbek Rustamov',
    phone: '+998 90 111 22 33',
    position: 'Frontend Developer',
    stage: 'applied',
    appliedAt: daysAgo(1),
    note: '3 yillik React tajribasi',
  },
  {
    id: 'cand-2',
    name: 'Nilufar Qodirova',
    phone: '+998 91 222 33 44',
    position: 'UI/UX Designer',
    stage: 'applied',
    appliedAt: daysAgo(2),
    note: 'Portfolio yuborilgan',
  },
  {
    id: 'cand-3',
    name: 'Shahzod Yusupov',
    phone: '+998 93 333 44 55',
    position: 'Backend Developer',
    stage: 'interview',
    appliedAt: daysAgo(4),
    note: "Texnik intervyu ertaga soat 14:00 da",
  },
  {
    id: 'cand-4',
    name: 'Madina Aliyeva',
    phone: '+998 94 444 55 66',
    position: 'HR Manager',
    stage: 'interview',
    appliedAt: daysAgo(5),
    note: "2-bosqich intervyudan o'tdi",
  },
  {
    id: 'cand-5',
    name: 'Bekzod Ismoilov',
    phone: '+998 95 555 66 77',
    position: 'DevOps Engineer',
    stage: 'offer',
    appliedAt: daysAgo(7),
    note: "Taklifnoma yuborildi, javob kutilmoqda",
  },
  {
    id: 'cand-6',
    name: 'Zarina Tosheva',
    phone: '+998 97 666 77 88',
    position: 'QA Engineer',
    stage: 'hired',
    appliedAt: daysAgo(12),
    note: "1-fevraldan ishga chiqadi",
  },
  {
    id: 'cand-7',
    name: 'Otabek Nazarov',
    phone: '+998 99 777 88 99',
    position: 'Mobile Developer',
    stage: 'rejected',
    appliedAt: daysAgo(9),
    note: "Talab qilingan tajriba yetarli emas",
  },
]

export const INITIAL_TELEGRAM_CHATS = [
  {
    id: 'tg-1',
    name: 'Sage Morgan',
    username: '@sage_morgan',
    unreadCount: 2,
    lastMessageAt: hoursAgo(1),
    messages: [
      { id: 'm1', from: 'them', text: "Assalomu alaykum! Narxlar bo'yicha savolim bor edi.", at: hoursAgo(2) },
      { id: 'm2', from: 'me', text: "Vaalaykum assalom! Albatta, marhamat so'rang.", at: hoursAgo(1.8) },
      { id: 'm3', from: 'them', text: 'Yillik obuna narxi qancha turadi?', at: hoursAgo(1) },
    ],
  },
  {
    id: 'tg-2',
    name: 'Sawyer Patel',
    username: '@sawyer_p',
    unreadCount: 0,
    lastMessageAt: hoursAgo(6),
    messages: [
      { id: 'm1', from: 'them', text: 'Rahmat, kelishuv uchun tayyormiz.', at: hoursAgo(6) },
      { id: 'm2', from: 'me', text: "Ajoyib! Shartnomani bugun jo'natamiz.", at: hoursAgo(5.5) },
    ],
  },
  {
    id: 'tg-3',
    name: 'Skyler Richardson',
    username: '@skyler_r',
    unreadCount: 5,
    lastMessageAt: hoursAgo(20),
    messages: [
      { id: 'm1', from: 'them', text: 'Demo versiyasini ko‘rish mumkinmi?', at: hoursAgo(21) },
      { id: 'm2', from: 'them', text: 'Va integratsiya haqida ham gaplashsak', at: hoursAgo(20) },
    ],
  },
]
